schema_version: 1

context:
  name: pygitguardian
  version: "1.21.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pygitguardian-${{ version }}.tar.gz
  sha256: e934ab00ff8ead8c6b149dc358d594ba3de41e68a93c10c95d0b72faf9506dfc

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pdm-backend
    - pip
  run:
    - python >=${{ python_min }}
    - marshmallow >=3.5,<4
    - requests >=2,<3
    - marshmallow-dataclass >=8.5.8,<8.6.0
    - typing_extensions
    - setuptools >=70.1.0

tests:
  - python:
      imports:
        - pygitguardian
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: "Python Wrapper for GitGuardian's API -- Scan security policy breaks everywhere"
  license: MIT
  license_file: LICENSE
  homepage: https://www.gitguardian.com

extra:
  recipe-maintainers:
    - janjagusch
